language: go

go:
  - 1.x

git:
  depth: 1

before_install:
#  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0
#  - go mod download
#  - golangci-lint --version

script:
  - go mod download && golangci-lint run -v
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
