language: go

go:
  - 1.11.x

git:
  depth: 1

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls

script:
  - gometalinter --config=gometalinter.json
  - $GOPATH/bin/goveralls -service=travis-ci
