language: go

go:
  - 1.11.x

git:
  depth: 1

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - go test -v -cover -race ./...
  - gometalinter --config=gometalinter.json
